name: terraform-lint

on: [pull_request]

jobs:
  terraform-pipeline:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate
        
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Exit status
        id: exit
        run: |
          if [ ${{ steps.plan.outputs.exitcode }} = 1 ]; then
            exit 1
          else
            exit 0
          fi
        shell: bash

    